### ISSUE TITLE
supports mobile terminal multiselect?

### ISSUE THREAD

**Issue by piyegui** [danhumphrey/Ext.ux.form.SuperBoxSelect#1]
hi！     The box supports mobile terminal multiselect?

**Comment by danhumphrey** [comment]
Hi @piyegui,

By saying `"mobile terminal"`, I assume that you mean a regular mobile phone or tablet? The component works on my mobile device, but certainly isn't optimized for mobile devices - this component was built for a version of the ext-js library which didn't support mobile as a first-class citizen.
