### ISSUE TITLE
LICENSE is missing

### ISSUE THREAD

**Issue by yury-yufimov** [danhumphrey/Ext.ux.form.SuperBoxSelect#2]
Hello.
Great and very useful extension, thank you!

We would like to use it in our project, but our security policy requires all used open-source libraries to have open licenses. 

Can you please add some LICENSE file to the project? For example, MIT license would be great

**Comment by danhumphrey** [comment]
Hi,

Glad you like it. MIT license added. 

Cheers,
Dan
